#ifndef TEACHINGTOOLS_GLOBAL_H
#define TEACHINGTOOLS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TEACHINGTOOLS_LIBRARY)
#  define TEACHINGTOOLS_EXPORT Q_DECL_EXPORT
#else
#  define TEACHINGTOOLS_EXPORT Q_DECL_IMPORT
#endif

#endif // TEACHINGTOOLS_GLOBAL_H
